name: Aside
description: Better multi-user private chat, sound notifications and name highlighting for mentioned players, and other assorted chat improvements.
version: 1.1
author: makskay
website: http://dev.bukkit.org/server-mods/Aside

main: me.makskay.bukkit.aside.AsidePlugin

commands:
  away:
    description: Toggle whether you're away. While away, incoming messages are saved for later viewing.
    usage: /<command> [message]
    permission: aside.user
    permission-message: You don't have permission to mark yourself as away from Minecraft!
  chatgroup:
    description: Create and edit groups to whom messages can be sent.
    usage: /<command> <group-name> <members|delete|+playername|-playername>
    aliases: [chat, ch]
    permission: aside.user
    permission-message: You don't have permission to create and edit groups!
  chatgroups:
    description: List the available groups.
    usage: /<command>
    aliases: [chats]
    permission: aside.user
    permission-message: You don't have permission to view the list of available groups!
  memos:
    description: View saved messages.
    usage: /<command> [-clear]
    permission: aside.user
    permission-message: You don't have permission to view saved messages!