name: Aside
description: Better multi-user private chat, sound notifications and name highlighting for mentioned players, and other assorted chat improvements.
version: 0.1.0
author: makskay

main: me.makskay.bukkit.aside.AsidePlugin